version: "3"

services:
  app:
    environment:
      - VARIANT=1.16
      - NODE_VERSION="lts/*"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - appdata:/workspace/
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    image: postgres:13.4
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword

volumes:
  appdata:
    driver: local
  pgdata:
    driver: local