version: "3"

services:
  app:
    environment:
      - VARIANT=1.16
      - NODE_VERSION="lts/*"
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace:cached
    ports:
      - 9000:9000
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:13.4
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      TZ: "Asia/Tokyo"

volumes:
  pgdata:
    driver: local